server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Если фронт шлет запросы на /api, Nginx перенаправит их в онлайн-бэк
    location /api/ {
        proxy_pass https://твой-онлайн-бек.com;
        proxy_set_header Host твой-онлайн-бек.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on; # Важно для HTTPS проксирования
    }
}